# - workflow - n4
#   - jobs - inspecao (bloco 1)
#     - steps - instalar dependencies
#     - steps - executar script de lint
#   - jobs - unidade (bloco 1)
#        -depende de: inspecao

#     - steps - instalar dependencies
#     - steps - executar script de testes de unidade
#   - jobs - e2e-tests (bloco 2)
#       -depende de: unidade  
#     - steps - instalar dependencies
#     - steps - instalar subir app localmente
#     - steps - instalar browsers
#     - steps - executar script de teste e2e
#     - steps - publicar resultados de testes(zip/online)

#   - jobs - deploy (bloco 3)
#        -depende de: e2e-tests
#     - steps - instalar depedendencies
#     - steps - gerar artefatos de aplicacao
#     - steps - publicar aplicação em algum ambiente

name: 'Execução Integrada'

on:
  workflow_dispatch:

jobs:
  inspecao:
    runs-on: ubuntu-latest
    #needs: [inspecao]

    steps:
      - uses: actions/checkout@v4

      - name: Instalando yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

  unidade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Executando testes de unidade
        run: yarn test

  e2e-tests:
    runs-on: ubuntu-latest
    #needs: [inspecao]

    steps:
      - uses: actions/checkout@v4

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Executando testes e2e
        run: yarn run e2e

        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: e2e-report
          path: ./playwright-report
          reporter: java-junit

  deploy:
    runs-on: ubuntu-latest
    #needs: [e2e-tests]

    steps:
      - name: Simulação de deploy
        run: echo "simulando deploy com sucesso"
